# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: [push]
jobs:     
  ballerina-hackathon-evaluator:      
    name: Run Ballerina Hackathon Evaluator    
    runs-on: ubuntu-latest       
    steps:    
    - name: Git checkout
      uses: actions/checkout@v2
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
    - name: Install redis  
      run: sudo apt-get install -y redis-tools redis-server    
    - name: Verify for redis is up
      run: redis-cli ping
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11 
    - name: Ballerina Download
      run: sudo wget http://dist-dev.ballerina.io/downloads/2201.0.0/ballerina-2201.0.0.zip
    - name: Use Ballerina zip version
      run: sudo apt-get install -y unzip
    - run: sudo unzip ballerina-2201.0.0.zip
      env: 
          JAVA_HOME: /usr/lib/jvm/default-jvm
          JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true 
    - name: Ballerina Run 
      run: /home/runner/work/testRepo/testRepo/ballerina-2201.0.0/bin/bal run test.bal
